name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
  id-token: write # For npm provenance
  attestations: write # For build attestations

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history for changelog generation
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: |
          pnpm typecheck
          pnpm lint
          pnpm test:node
          pnpm test:workers
      
      - name: Build package
        run: pnpm build
      
      - name: Check bundle size
        run: pnpm size
      
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: |
            dist/**/*.js
            dist/**/*.cjs
            dist/**/*.d.ts
            dist/**/*.d.cts
            package.json
      
      - name: Set version (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      
      - name: Extract version (tag trigger)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Publish to npm
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            ## @tenderlift/zefix-client v${{ env.VERSION }}
            
            ### Installation
            ```bash
            npm install @tenderlift/zefix-client@${{ env.VERSION }}
            # or
            pnpm add @tenderlift/zefix-client@${{ env.VERSION }}
            ```
            
            ### What's Changed
            See [CHANGELOG.md](https://github.com/TenderLift/zefix-client/blob/v${{ env.VERSION }}/CHANGELOG.md) for details.
            
            ### Bundle Size
            Check the [size report](https://github.com/TenderLift/zefix-client/actions/runs/${{ github.run_id }}) for this release.
            
            ---
            **Full Changelog**: https://github.com/TenderLift/zefix-client/compare/v${{ env.PREVIOUS_VERSION }}...v${{ env.VERSION }}
          files: |
            dist/**/*.js
            dist/**/*.cjs
            dist/**/*.d.ts
          draft: false
          prerelease: ${{ contains(env.VERSION, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-v${{ env.VERSION }}
          path: |
            dist/
            package.json
            README.md
            LICENSE
            NOTICE
            CHANGELOG.md
          retention-days: 90